### ISSUE TITLE
Mastodon stream not showing up at all

### ISSUE THREAD

**Issue by offerman** [nikosdion/fediverse#10]
Hi,

I installed pkg_fediverse-2.0.0.zip and created a new module to display my Mastodon stream as per the manual. But nothing shows up (not even a trace in the HTML source code). I checked/changed the Position several times to make sure that I didn't make a mistake there, but to no avail.

I'm assuming this is just me overlooking something obvious. Any hints?

### System information
- Joomla! 4.3.1 Stable
- Cassiopeia
- PHP 8.0.20
- Firefox 111.0 & Chromium 111.0.5563.110

![screenshot1](https://user-images.githubusercontent.com/3305099/236559425-284a9a52-2c22-4005-9670-63d9486abf6d.png)
![screenshot2](https://user-images.githubusercontent.com/3305099/236559454-9f919488-de0e-43d7-bd45-24f4bf0abc8f.png)
![screenshot3](https://user-images.githubusercontent.com/3305099/236559490-fb1d5916-f93a-4516-b612-3df26d2722ff.png)

**Comment by nikosdion** [comment]
Edit the file `modules\mod_fediversefeed\services\provider.php`.

Replace the two instances of `\\Joomla\\Module` with `\\Dionysopoulos\\Module` (lines 34 and 35).

**Comment by offerman** [comment]
Fixed now!
Thanks for quick response!

**Comment by jamfx** [comment]
I ran into the same issue. And the provided fix worked.

**Comment by nikosdion** [comment]
Thank you for the feedback, folks! I will have to release a new version of the extension :)
