### ISSUE TITLE
Crashing Pageload under some conditions

### ISSUE THREAD

**Issue by jamfx** [nikosdion/fediverse#12]
### Steps to reproduce the issue
Install latest Fedi-Package 2.0.1

### Expected result
Toots are loaded and page is loading properly

### Actual result
I think the toots are breaking the pageload. 
Latest posts are visible here:
-> I think this post broke it. 
https://mstdn.social/@feditips/111104292329970824

### Troubleshooting already performed
Unpublish Toot-Module -> site loads perfect

### System information
* **Joomla! version**: “ ‎4.3.4
* **Joomla! frontend template**: JoomlaPlates TP Technlogy
* **PHP version**: 8.2.10 
* **Browser (name and version)**: Firefox 117.0.1 

Error Report:
| --- | --- | --- |
| **#** | **Function** | **Location** |
| 1 | () | JROOT/libraries/src/Language/Text.php:281 |
| 2 | sprintf() | JROOT/libraries/src/Language/Text.php:281 |
| 3 | Joomla\\CMS\\Language\\Text::sprintf() | JROOT/modules/mod\_fediversefeed/tmpl/default\_media.php:79 |
| 4 | require() | JROOT/modules/mod\_fediversefeed/tmpl/default\_toot.php:71 |
| 5 | require() | JROOT/modules/mod\_fediversefeed/tmpl/default.php:124 |
| 6 | require() | JROOT/libraries/src/Dispatcher/AbstractModuleDispatcher.php:87 |
| 7 | Joomla\\CMS\\Dispatcher\\AbstractModuleDispatcher::Joomla\\CMS\\Dispatcher\\{closure}() | JROOT/libraries/src/Dispatcher/AbstractModuleDispatcher.php:90 |
| 8 | Joomla\\CMS\\Dispatcher\\AbstractModuleDispatcher->dispatch() | JROOT/libraries/src/Helper/ModuleHelper.php:281 |
| 9 | Joomla\\CMS\\Helper\\ModuleHelper::renderRawModule() | JROOT/libraries/src/Helper/ModuleHelper.php:161 |
| 10 | Joomla\\CMS\\Helper\\ModuleHelper::renderModule() | JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:99 |
| 11 | Joomla\\CMS\\Document\\Renderer\\Html\\ModuleRenderer->render() | JROOT/libraries/src/Document/Renderer/Html/ModulesRenderer.php:50 |
| 12 | Joomla\\CMS\\Document\\Renderer\\Html\\ModulesRenderer->render() | JROOT/libraries/src/Document/HtmlDocument.php:566 |
| 13 | Joomla\\CMS\\Document\\HtmlDocument->getBuffer() | JROOT/libraries/src/Document/HtmlDocument.php:853 |
| 14 | Joomla\\CMS\\Document\\HtmlDocument->\_renderTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:638 |
| 15 | Joomla\\CMS\\Document\\HtmlDocument->render() | JROOT/libraries/src/Application/CMSApplication.php:1025 |
| 16 | Joomla\\CMS\\Application\\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:724 |
| 17 | Joomla\\CMS\\Application\\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:298 |
| 18 | Joomla\\CMS\\Application\\CMSApplication->execute() | JROOT/includes/app.php:61 |
| 19 | require\_once() | JROOT/index.php:32 |

**Comment by jamfx** [comment]
Ok, I found out, that a Toot with an Audiofile is causing the Problem!
And if I remove %u from the Language-String: 
MOD_FEDIVERSEFEED_ERR_UNSUPPORTED_MEDIA=...
I then get a human readable Error-Message with a hint to the Audio-File.
 It's this toot btw: https://mastodontech.de/@nikomat/111104182559786312
I hope this helps

**Comment by nikosdion** [comment]
Thank you!

**Comment by nikosdion** [comment]
It also looks like there is a problem in the German translation, but not in other languages. I will fix that too.
