### ISSUE TITLE
Question: Use the fediverse-tools with existing account from another server

### ISSUE THREAD

**Issue by geocoderEU** [nikosdion/fediverse#14]
Hello,

as far as i understood, this plugin allows me to convert my joomla installation into an activitypub server. With own username, etc..
My current situation is as follows: 

Our organization has a joomla website where we post articles. We also have a seperate mastodon account on an instance we don't own. So currenty we post all things in that mastodon account seperatly. 

So the question ist: would it be possible to let the plugin autopost the article via the existing account?

**Comment by nikosdion** [comment]
It wouldn't autopost to a different instance, your site would appear as its own instance on the fediverse and your articles would appear as posts made on this instance. You need a different kind of extension for what you are trying to do. Maybe look in the JED, the extensions which autopost to Facebook, Twitter etc could conceivably create an integration with Mastodon. The API is fairly straightforward and they already have in place everything they need to autopost new articles to an external service.
